/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/nintendo_switch/nintendo_switch.glb 
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'
import { useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useGSAP } from '@gsap/react';
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'


const useSwitchRef = () => {
  const myRef = useRef();
  
  return myRef;
}

export function Switch(props) {
  const group = useSwitchRef();
  const { nodes, materials } = useGLTF('/models/nintendo_switch/nintendo_switch.glb')

  const tl = gsap.timeline();
  
  /*useGSAP(
    () => {
      tl.to(
        group.current.rotation,
        {
          duration: 1.5,
          x: '+=2.56',
          y: '+=-1.01',
          z: '+=2',
          ease: 'power1.inOut',
          scrollTrigger: {
            trigger: '.section-2',
            start: 'top bottom',
            end: 'bottom bottom',
            scrub: 0.5
          }
        }
      )
    }
  );

  */
  useFrame((state, delta) => {
   if(group.current) group.current.rotation.y += delta * 0.1;
  })

 
  return (
    <group  ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Plane002_0.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Plane002_2.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Plane002_3.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.Plane002_4.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.Plane_0.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.008']} />
      <mesh geometry={nodes.Plane001_0.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.008']} />
      <mesh geometry={nodes.Plane001_3.geometry} material={materials['Material.009']} />
    </group>
  )
}

useGLTF.preload('/nintendo_switch.glb')

export { useSwitchRef };