/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ps5/playstation_5.glb 
Author: MG990 (https://sketchfab.com/MG990)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/playstation-5-d95c5ed0b73e4fdc8a982409a495f3a8
Title: PlayStation 5
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PS5(props) {
  const { nodes, materials } = useGLTF('/models/ps5/playstation_5.glb')
  return (
    <group {...props} position={[0,-16,0]} dispose={null}>
      <group position={[-0.053, 1.216, -0.169]} rotation={[-3.141, 1.569, 1.571]} scale={0.801}>
        <mesh geometry={nodes.Object_48.geometry} material={materials.white} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.material_0} />
      </group>
      <group position={[-0.061, 1.237, 0.069]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.801, 0.801, 0.801]}>
        <mesh geometry={nodes.Object_51.geometry} material={materials.white} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.black} />
      </group>
      <group position={[0.429, 2.248, -0.018]}>
        <mesh geometry={nodes.Object_54.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.blue_light} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.black} position={[-0.495, 2.383, -0.16]} rotation={[-0.041, 0.039, 0.002]} scale={[0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.black} position={[0.393, 2.378, -0.192]} rotation={[-0.035, 0.045, -0.142]} scale={[0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.black} position={[0.438, 2.366, -0.192]} rotation={[-0.024, 0.015, -0.362]} scale={[0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.black} position={[0.479, 2.345, -0.192]} rotation={[-0.052, 0.056, -0.583]} scale={[0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.black} position={[0.511, 2.318, -0.192]} rotation={[-0.055, 0.057, -0.763]} scale={[0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.black} position={[0.539, 2.286, -0.192]} rotation={[-0.071, 0.056, -0.947]} scale={[0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.black} position={[0.559, 2.249, -0.192]} rotation={[-0.053, 0.053, -1.157]} scale={[0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.black} position={[0.572, 2.208, -0.189]} rotation={[-0.046, 0.05, -1.289]} scale={[0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.black} position={[0.576, 2.169, -0.186]} rotation={[-0.042, 0.042, -1.553]} scale={[0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.black} position={[0.577, 2.13, -0.19]} rotation={[-0.051, 0.041, -Math.PI / 2]} scale={[0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.black} position={[0.577, 1.239, -0.14]} rotation={[-0.048, 0.041, -Math.PI / 2]} scale={[0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.black} position={[-0.498, 2.384, 0.138]} rotation={[3.101, 0.03, -3.14]} scale={[-0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.black} position={[0.393, 2.378, 0.165]} rotation={[3.095, -0.034, -3]} scale={[-0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.black} position={[0.438, 2.366, 0.162]} rotation={[3.084, -0.064, -2.781]} scale={[-0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.black} position={[0.479, 2.345, 0.161]} rotation={[3.112, -0.023, -2.558]} scale={[-0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.black} position={[0.511, 2.318, 0.161]} rotation={[3.115, -0.022, -2.377]} scale={[-0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.black} position={[0.539, 2.286, 0.161]} rotation={[3.13, -0.023, -2.192]} scale={[-0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.black} position={[0.559, 2.249, 0.162]} rotation={[3.112, -0.026, -1.983]} scale={[-0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.black} position={[0.572, 2.208, 0.161]} rotation={[3.105, -0.029, -1.852]} scale={[-0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.black} position={[0.575, 2.169, 0.162]} rotation={[3.102, -0.037, -1.589]} scale={[-0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.black} position={[0.577, 2.122, 0.155]} rotation={[-3.076, -0.038, -1.57]} scale={[-0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.black} position={[0.577, 1.237, 0.099]} rotation={[-3.097, 0.041, -Math.PI / 2]} scale={[-0.008, 0.008, 0.019]} />
      <mesh geometry={nodes.Object_57.geometry} material={materials.black} position={[-0.659, 0.078, -0.051]} scale={0.167} />
      <mesh geometry={nodes.Object_59.geometry} material={materials.black} position={[-0.073, 0.055, -0.056]} rotation={[0, 0, -Math.PI]} scale={[0.472, 0.057, 0.472]} />
      <mesh geometry={nodes.Object_61.geometry} material={materials.metal} position={[0.591, 1.218, -0.028]} scale={[0.973, 0.973, 0.932]} />
      <mesh geometry={nodes.Object_63.geometry} material={materials.metal} position={[0.596, 1.096, -0.028]} scale={[0.964, 1.032, 0.948]} />
      <mesh geometry={nodes.Object_65.geometry} material={materials.gray} position={[0.578, 1.217, -0.018]} />
    </group>
  )
}

useGLTF.preload('/playstation_5.glb')
