/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/playstation_4_pro/PS4.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function PS4(props) {
  const { nodes, materials } = useGLTF('/models/playstation_4_pro/PS4.glb')

  const group = useRef();
   useFrame((state, delta) => {
     if(group.current) group.current.rotation.y += delta * 0.1;
   })
  
  return (
    <group ref={group} position ={[0,-8,0]}{...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Playstation_4_Pro_Console_MATERIAL} />
    </group>
  )
}

useGLTF.preload('/models/playstation_4_pro/PS4.glb')
