/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/xbox_series_x/XBOX.glb 
*/

import React, { useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function XBOX(props) {
  const { nodes, materials } = useGLTF('/models/xbox_series_x/XBOX.glb');

  const group = useRef();
   useFrame((state, delta) => {
     if(group.current) group.current.rotation.y += delta * 0.1;
    })
  return (
    <group ref={group} position ={[0,-16,0]}{...props} dispose={null}>
      <mesh geometry={nodes.BOX_BOX_VENT_0.geometry} material={materials.BOX_VENT} />
      <mesh geometry={nodes.VENT_BOX_VENT_0.geometry} material={materials.BOX_VENT} />
      <mesh geometry={nodes.GLOW_GLOW_GREEN_0.geometry} material={materials.GLOW_GREEN} />
      <mesh geometry={nodes.LOGOX_LOGOX_0.geometry} material={materials.LOGOX} />
    </group>
  )
}

useGLTF.preload('/models/xbox_series_x/XBOX.glb')
