/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/xbox_one/xbox_one.glb 
Author: Daz (https://sketchfab.com/Darren.Hogan)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/xbox-one-8866e33768e84b27b69e07abcde8a593
Title: Xbox One
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/xbox_one.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[1.576, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
          <group position={[-2.216, 0.923, -0.31]}>
            <mesh geometry={nodes.XboxOne_Matte_0.geometry} material={materials.Matte} />
            <mesh geometry={nodes.XboxOne_Gloss_0.geometry} material={materials.Gloss} />
            <mesh geometry={nodes.XboxOne_Power_0.geometry} material={materials.Power} />
            <mesh geometry={nodes.XboxOne_Metal_0.geometry} material={materials.Metal} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/xbox_one.glb')
