/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/xbox_series_x/xbox_series_x.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Xbox(props) {
  const { nodes, materials } = useGLTF('/models/xbox_series_x/xbox_series_x.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.002}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.BOX_BOX_VENT_0.geometry} material={materials.BOX_VENT} />
            <mesh geometry={nodes.VENT_BOX_VENT_0.geometry} material={materials.BOX_VENT} position={[-0.818, 0.982, 4.078]} rotation={[0, 0, -Math.PI / 2]} />
          </group>
          <mesh geometry={nodes.GLOW_GLOW_GREEN_0.geometry} material={materials.GLOW_GREEN} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.LOGOX_LOGOX_0.geometry} material={materials.LOGOX} position={[100.251, 370.541, 73.152]} rotation={[0, 1.571, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/xbox_series_x.glb')
